spring:
  data:
    redis:
      host: 192.168.0.10
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
  rabbitmq:
    username: root
    password: WHkdy123@
    host: 192.168.0.10
